const fs = require('fs');
const path = require('path');

const seedFile = path.join(__dirname, '../data/seedData.ts');
let content = fs.readFileSync(seedFile, 'utf8');

const updatedExperiences = `export const seedExperiences = [
  {
    title: "Things to See",
    name: "Things to See",
    slug: "things-to-see",
    category: "Sightseeing & Heritage",
    badge: "Nature",
    badgeColor: "bg-blue-600",
    shortDescription: "Discover Sri Lanka's iconic landmarks, ancient cities, scenic viewpoints, and hidden gems.",
    description:
      "From the monumental 5th-century rock citadel of Sigiriya rising dramatically above emerald jungle canopies, to the iconic Nine Arch Bridge nestled in Ella's mist-laden tea hills, and the UNESCO-listed 16th-century ocean ramparts of Galle Fort, Sri Lanka offers an awe-inspiring tapestry of world-famous landmarks and hidden geographical treasures. Explore sacred ancient kingdoms, panoramic alpine lookouts at World's End, cascading waterfalls, and tropical coastal headlands that define the island's legendary beauty.",
    image: "/images/destinations/sigiriya-lion-rock-monumental.jpg",
    images: [
      "/images/destinations/sigiriya-lion-rock-monumental.jpg",
      "/images/destinations/ella-nine-arch-bridge.jpg",
      "/images/destinations/galle-fort-lighthouse.jpg",
      "/images/destinations/kandy-temple-tooth-sunset.jpg",
      "/images/destinations/mirissa-coconut-tree-hill-hills.jpg",
      "/images/destinations/polonnaruwa-vatadage-1.jpg",
      "/images/destinations/sigiriya-pidurangala-viewpoint.jpg",
    ],
    duration: "Full-Day / Multi-Day",
    difficulty: "Easy to Moderate",
    bestSeason: "November to April (South/West) & May to September (East/North)",
    location: "Islandwide (Central, Southern & Uva Provinces)",
    destinations: ["Sigiriya", "Ella", "Galle", "Kandy", "Mirissa"],
    featured: true,
    highlights: [
      "Sigiriya Lion Rock Fortress UNESCO archaeological marvel",
      "Demodara Nine Arch stone railway viaduct in Ella",
      "16th-century Galle Fort UNESCO ocean ramparts and lighthouse",
      "Temple of the Sacred Tooth Relic beside Kandy Lake",
      "World's End 1,000-meter sheer precipice in Horton Plains",
      "Mirissa Coconut Tree Hill panoramic ocean vista",
    ],
    whyExperience: [
      "Witness millennia of living history and royal stone engineering",
      "Capture world-class photography from celebrated viewpoints",
      "Travel seamlessly between cool mountain tea slopes and warm tropical beaches",
      "Discover ancient rock frescoes, water gardens, and colonial ramparts",
    ],
    popularPlaces: [
      {
        name: "Sigiriya Lion Rock Citadel",
        description: "Colossal ancient rock fortress and UNESCO World Heritage archaeological marvel.",
        district: "Matale",
      },
      {
        name: "Nine Arch Bridge",
        description: "World-famous 1921 British colonial stone railway viaduct surrounded by tea hills.",
        district: "Badulla",
      },
      {
        name: "Galle Fort & Lighthouse",
        description: "Atmospheric 16th-century Dutch colonial sea fortress and ramparts.",
        district: "Galle",
      },
      {
        name: "Temple of the Sacred Tooth Relic",
        description: "Sri Lanka's most sacred Buddhist temple beside scenic Kandy Lake.",
        district: "Kandy",
      },
      {
        name: "Coconut Tree Hill",
        description: "Picturesque palm-covered coastal headland overlooking the Indian Ocean in Mirissa.",
        district: "Matara",
      },
    ],
    thingsToDo: [
      "Climb Sigiriya at sunrise for 360-degree panoramic jungle views",
      "Watch the blue train cross Demodara Nine Arch Bridge amid tea plantations",
      "Walk the cobblestone pathways and ocean ramparts of Galle Fort",
      "Visit the gilded shrine of the Temple of the Sacred Tooth in Kandy",
      "Hike to Little Adam's Peak and gaze across Ella Gap",
    ],
    travelTips: [
      "Start early in the morning for Sigiriya and mountain viewpoints to avoid midday heat",
      "Wear modest attire covering shoulders and knees when visiting sacred temples",
      "Book scenic hill country train tickets in advance for reserved observation seats",
      "Carry ample drinking water and sun protection during outdoor excursions",
    ],
  },
  {
    title: "Pilgrimage & Sacred Shrines",
    name: "Pilgrimage & Sacred Shrines",
    slug: "pilgrimage-sacred-shrines",
    category: "Spiritual & Culture",
    badge: "Culture",
    badgeColor: "bg-purple-600",
    shortDescription: "Explore Sri Lanka's sacred temples, kovils, shrines, and centuries-old pilgrimage traditions.",
    description:
      "Sri Lanka is deeply revered as a cradle of Theravada Buddhism and ancient Hindu devotion, home to some of the world's most venerated spiritual monuments. Pilgrims from across the globe journey to worship at the Temple of the Sacred Tooth Relic (Sri Dalada Maligawa) in Kandy, the 2,300-year-old Jaya Sri Maha Bodhi tree in Anuradhapura, the colossal snow-white Ruwanwelisaya stupa, the ancient Pancha Ishwaram Shiva temples like Munneswaram Kovil, the sacred multi-faith jungle shrine of Kataragama, and the towering ornate Gopurams of Nallur Kandaswamy Kovil in Jaffna.",
    image: "/images/destinations/kandy-temple-tooth-sunset.jpg",
    images: [
      "/images/destinations/kandy-temple-tooth-sunset.jpg",
      "/images/culture/hindu-kovil-chariot.jpg",
      "/images/destinations/seruwawila-stupa-main.jpg",
      "/images/destinations/munneswaram-kovil-gopuram.jpg",
      "/images/destinations/polonnaruwa-vatadage-1.jpg",
      "/images/destinations/jaffna-kovil-1.jpg",
      "/images/culture/monks-pindapatha.jpg",
      "/images/destinations/kandy-temple-night-lights.jpg",
    ],
    duration: "Half-Day to Multi-Day Pilgrimage",
    difficulty: "Easy & Reflective",
    bestSeason: "Year-Round (Poya Full Moon Days are especially sacred)",
    location: "Kandy, Anuradhapura, Jaffna, Chilaw & Kataragama",
    destinations: ["Kandy", "Anuradhapura", "Jaffna", "Polonnaruwa", "Seruwawila"],
    featured: true,
    highlights: [
      "Sacred Tooth Relic of Gautama Buddha at Sri Dalada Maligawa",
      "Jaya Sri Maha Bodhi—the oldest recorded human-planted tree",
      "Colossal Ruwanwelisaya and Jetavanaramaya ancient stupas",
      "Pancha Ishwaram Munneswaram Shiva Kovil with Dravidian Gopuram",
      "Multi-faith Kataragama jungle shrine and fire-walking rituals",
      "2nd-century BCE Seruwawila Mangala Raja Maha Viharaya",
    ],
    whyExperience: [
      "Immerse in thousands of years of uninterrupted living devotional rituals",
      "Witness fragrant jasmine flower offerings and hypnotic oil lamp lighting",
      "Experience multi-faith harmony where Buddhists, Hindus, Muslims, and Christians worship peacefully",
      "Appreciate ancient stone carvings, moonstones, and sacred temple murals",
    ],
    popularPlaces: [
      {
        name: "Temple of the Sacred Tooth Relic",
        description: "Royal palace temple housing the Buddha's tooth relic in sacred Kandy.",
        district: "Kandy",
      },
      {
        name: "Ruwanwelisaya Stupa",
        description: "Colossal 2nd-century BCE white stupa built by King Dutugemunu.",
        district: "Anuradhapura",
      },
      {
        name: "Nallur Kandaswamy Kovil",
        description: "Magnificent Hindu temple with towering ornate golden Gopuram in Jaffna.",
        district: "Jaffna",
      },
      {
        name: "Munneswaram Kovil",
        description: "Ancient Pancha Ishwaram dedicated to Lord Shiva linked to the Ramayana.",
        district: "Puttalam",
      },
      {
        name: "Seruwawila Mangala Raja Maha Viharaya",
        description: "Sacred stupa enshrining the Lalata Dathu (forehead bone relic).",
        district: "Trincomalee",
      },
    ],
    thingsToDo: [
      "Participate in the morning or evening Thevava drumming ceremony at Dalada Maligawa",
      "Offer fragrant lotus flowers at the base of ancient white stupas",
      "Witness the vibrant Nallur Ther chariot procession in Jaffna",
      "Receive sacred ash (Vibhuti) blessings at Munneswaram Kovil",
      "Meditate peacefully beneath the sacred Jaya Sri Maha Bodhi tree",
    ],
    travelTips: [
      "Wear pure white or modest light-colored clothing covering knees and shoulders",
      "Remove hats, headwear, and footwear before entering temple premises",
      "Walk clockwise (Pradakshina) around stupas and sacred shrines",
      "Photography of Buddha statues with people posing with backs turned is strictly prohibited",
    ],
  },
  {
    title: "Ayurveda & Healing",
    name: "Ayurveda & Healing",
    slug: "ayurveda-healing",
    category: "Ayurveda & Wellness",
    badge: "Wellness",
    badgeColor: "bg-emerald-600",
    shortDescription: "Experience ancient Sri Lankan Ayurveda therapies, herbal remedies, and traditional healing practices.",
    description:
      "Sri Lanka possesses an indigenous system of traditional healing (Deshiya Chikitsa) refined over 5,000 years alongside classical Ayurveda. Under the guidance of certified Ayurvedic doctors (Vaidyas), treatments are tailored to balance the body's three vital energies (Doshas: Vata, Pitta, and Kapha). Experiences feature customized herbal oil body massages (Abhyanga), warm medicated oil stream therapy onto the forehead (Shirodhara), full-body herbal steam baths (Swedana), herbal leaf compresses, and fresh detoxifying herbal tonics prepared from native flora.",
    image: "https://images.unsplash.com/photo-1540555700478-4be289fbecef?q=80&w=1200&auto=format&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1540555700478-4be289fbecef?q=80&w=1200&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1512290900672-1f41b590e44c?q=80&w=1200&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1506126613408-eca07ce68773?q=80&w=1200&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1600334089648-b0d9d3028eb2?q=80&w=1200&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1515377905703-c4788e51af15?q=80&w=1200&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1544161515-4ab6ce6db874?q=80&w=1200&auto=format&fit=crop",
    ],
    duration: "Half-Day / 3 to 14 Days Retreat",
    difficulty: "Relaxing & Restorative",
    bestSeason: "Year-Round (Monsoon periods May-Jun & Oct-Nov are traditionally ideal for treatments)",
    location: "Bentota, Beruwala, Kandy, Tangalle",
    destinations: ["Galle", "Kandy", "Ella", "Mirissa"],
    featured: true,
    highlights: [
      "In-depth personalized consultation with certified Ayurvedic physicians",
      "Shirodhara rhythmic warm herbal oil therapy for mental tranquility",
      "Full-body Abhyanga massage with medicated herbal oils",
      "Traditional herbal leaf steam baths and detoxifying clay wraps",
      "Customized dietary plans utilizing medicinal spices and herbal infusions",
      "Botanical garden walks explaining traditional healing herbs",
    ],
    whyExperience: [
      "Purify your body from accumulated stress and environmental toxins",
      "Restore deep energetic balance and improve sleep quality",
      "Experience pure herbal elixirs prepared from fresh tropical roots and leaves",
      "Learn ancient lifestyle habits and mindful wellness wisdom for daily living",
    ],
    popularPlaces: [
      {
        name: "Bentota & Beruwala Ayurvedic Sanctuaries",
        description: "World-renowned specialized coastal Ayurveda hospitals and retreats.",
        district: "Galle",
      },
      {
        name: "Kandy Valley Herbal Retreats",
        description: "Tranquil highland wellness centers nestled amidst cool tea slopes.",
        district: "Kandy",
      },
      {
        name: "Tangalle & Weligama Wellness Lodges",
        description: "Peaceful oceanfront sanctuaries integrating ocean breezes with Ayurveda.",
        district: "Matara",
      },
      {
        name: "Matale Herbal Sanctuaries",
        description: "Traditional medicine centers adjoining living spice gardens.",
        district: "Matale",
      },
    ],
    thingsToDo: [
      "Undergo a comprehensive pulse diagnosis (Nadi Pariksha) consultation",
      "Experience daily morning Shirodhara and herbal oil massages",
      "Relax inside a traditional wooden herbal steam box with medicinal leaves",
      "Enjoy customized tri-doshic meals prepared with organic farm ingredients",
      "Practice gentle dawn restorative yoga and breathwork (Pranayama)",
    ],
    travelTips: [
      "Commit to at least 3 to 7 days for deep therapeutic detoxification results",
      "Refrain from heavy alcohol and processed foods during Ayurvedic treatments",
      "Drink warm boiled water and herbal infusions throughout your retreat",
      "Inform your Ayurvedic doctor about any existing medical conditions or allergies",
    ],
  },
  {
    title: "Spa & Wellness",
    name: "Spa & Wellness",
    slug: "spa-wellness",
    category: "Spa & Relaxation",
    badge: "Wellness",
    badgeColor: "bg-emerald-600",
    shortDescription: "Relax and rejuvenate with luxurious spa treatments and wellness experiences surrounded by Sri Lanka's tropical beauty.",
    description:
      "Sri Lanka's luxury spa resorts provide exquisite sensory sanctuaries set amidst tropical palm groves, tranquil inland waterways, and cliffside ocean lookouts. Indulge in aromatic floral baths, hot stone massages with virgin coconut oil, Ceylon black tea body scrubs, aloe vera soothing body wraps, and sound-healing meditation sessions. Master therapists blend international luxury standards with Sri Lankan warmth to offer complete physical revitalization.",
    image: "https://images.unsplash.com/photo-1544161515-4ab6ce6db874?q=80&w=1200&auto=format&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1544161515-4ab6ce6db874?q=80&w=1200&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1507652313519-d4e9174996dd?q=80&w=1200&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1540555700478-4be289fbecef?q=80&w=1200&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1519710164239-da123dc03ef4?q=80&w=1200&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?q=80&w=1200&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1506126613408-eca07ce68773?q=80&w=1200&auto=format&fit=crop",
    ],
    duration: "1 to 4 Hours / Multi-Day Package",
    difficulty: "Pure Relaxation",
    bestSeason: "Year-Round",
    location: "Galle, Nuwara Eliya, Sigiriya, Colombo, Bentota",
    destinations: ["Galle", "Nuwara Eliya", "Colombo", "Mirissa"],
    featured: true,
    highlights: [
      "Exquisite open-air pavilion suites overlooking oceans and lotus lagoons",
      "Organic Ceylon Green Tea and crushed spice body exfoliations",
      "Signature virgin coconut and frangipani aromatherapies",
      "Thermal hydrotherapy pools, sauna, and ocean-facing plunge baths",
      "Private sunrise yoga and Tibetan singing bowl sound meditation",
      "Couples holistic massage rituals in candlelit tropical gardens",
    ],
    whyExperience: [
      "Unwind in ultra-luxurious, world-class resort spas",
      "Pamper your senses with natural, locally sourced botanicals",
      "Recharge your energy amidst peaceful tropical birdsong and ocean sounds",
      "Experience world-renowned Sri Lankan hospitality and gentle touch",
    ],
    popularPlaces: [
      {
        name: "Southern Coastal Boutique Spas",
        description: "Luxury clifftop and beachfront wellness resorts in Galle, Tangalle, and Weligama.",
        district: "Galle",
      },
      {
        name: "Tea Country Highland Spas",
        description: "Mist-enshrouded colonial tea estate wellness chalets in Nuwara Eliya and Hatton.",
        district: "Nuwara Eliya",
      },
      {
        name: "Cultural Triangle Nature Spas",
        description: "Eco-luxury wellness sanctuaries set beside ancient lakes in Sigiriya and Dambulla.",
        district: "Matale",
      },
      {
        name: "Colombo City Urban Retreats",
        description: "Five-star rooftop spa sanctuaries overlooking the Indian Ocean skyline.",
        district: "Colombo",
      },
    ],
    thingsToDo: [
      "Book a signature 3-hour Ceylon tea and spice spa ritual",
      "Soak in a copper bathtub infused with fresh frangipani and lotus petals",
      "Join an oceanfront sunset Vinyasa yoga class",
      "Experience a deep tissue hot stone massage with heated river stones",
      "Sip freshly plucked herbal teas in an open-air relaxation lounge",
    ],
    travelTips: [
      "Arrive 20-30 minutes early to enjoy the steam rooms and relaxation facilities",
      "Communicate your pressure preferences and focus areas clearly to your therapist",
      "Drink plenty of mineral water after treatments to flush released toxins",
      "Schedule spa sessions in the late afternoon to unwind after sightseeing",
    ],
  },
  {
    title: "Eco Tourism & Wildlife",
    name: "Eco Tourism & Wildlife",
    slug: "eco-tourism-wildlife",
    category: "Wildlife & Nature",
    badge: "Nature",
    badgeColor: "bg-blue-600",
    shortDescription: "Discover Sri Lanka's extraordinary wildlife, national parks, forests, and responsible eco-tourism experiences.",
    description:
      "Sri Lanka is globally recognized as one of the world's top 36 biodiversity hotspots. With 26 national parks spanning dry-zone savannahs, montane cloud forests, and tropical rainforests like Sinharaja, the island is famed for 'The Big Four': the majestic Sri Lankan Asian Elephant, the elusive Sri Lankan Leopard (Panthera pardus kotiya), the shaggy Sloth Bear, and the mighty Blue Whale off its coasts. Visitors on responsible 4x4 open safari jeeps traverse untouched landscapes with certified naturalists who prioritize animal conservation and habitat protection.",
    image: "/images/destinations/yala-elephant-family.jpg",
    images: [
      "/images/destinations/yala-elephant-family.jpg",
      "/images/destinations/yala-leopard-portrait.jpg",
      "/images/destinations/yala-leopard-tree.jpg",
      "/images/destinations/yala-safari-jeep-gathering.jpg",
      "/images/destinations/yala-elephants-sunset.jpg",
      "/images/destinations/pinnawala-elephants-river.jpg",
      "/images/destinations/pinnawala-elephant-family.jpg",
    ],
    duration: "Half-Day / Full-Day Safari",
    difficulty: "Easy",
    bestSeason: "February to July (Yala & Wilpattu) & August to October (Minneriya Elephant Gathering)",
    location: "Yala, Udawalawe, Minneriya, Wilpattu, Sinharaja",
    destinations: ["Yala", "Pinnawala", "Anuradhapura", "Polonnaruwa"],
    featured: true,
    highlights: [
      "World's highest density of leopards in Yala and Wilpattu National Parks",
      "The 'Elephant Gathering' of 300+ wild elephants in Minneriya and Kaudulla",
      "Guaranteed wild elephant sightings in Udawalawe National Park",
      "UNESCO Sinharaja Biosphere Reserve with 95% endemic bird species",
      "Responsible community-based eco-lodges and conservation safaris",
      "Whale watching in Mirissa and Trincomalee marine reserves",
    ],
    whyExperience: [
      "Encounter wild Asian elephants and leopards in their natural habitats",
      "Support local conservation efforts and sustainable park management",
      "Photograph over 400 species of resident and migratory tropical birds",
      "Experience breathtaking savannah sunrises and pristine jungle nights",
    ],
    popularPlaces: [
      {
        name: "Yala National Park",
        description: "World-famous dry-zone wildlife sanctuary with top leopard density.",
        district: "Hambantota",
      },
      {
        name: "Udawalawe National Park",
        description: "Premier wild elephant sanctuary surrounding a colossal reservoir.",
        district: "Ratnapura",
      },
      {
        name: "Minneriya & Kaudulla",
        description: "Ancient reservoirs hosting the world-famous seasonal Elephant Gathering.",
        district: "Polonnaruwa",
      },
      {
        name: "Wilpattu National Park",
        description: "Sri Lanka's largest national park featuring natural sand-rimmed water basins.",
        district: "Anuradhapura",
      },
      {
        name: "Sinharaja Rainforest",
        description: "UNESCO World Heritage virgin tropical lowland rainforest.",
        district: "Ratnapura",
      },
    ],
    thingsToDo: [
      "Embark on a sunrise 4x4 leopard and elephant tracking safari",
      "Witness playful elephant calves nursing and bathing at park waterholes",
      "Join a guided birdwatching trek in Sinharaja rainforest canopy",
      "Observe wild sloth bears feeding on sweet Palu fruits in July",
      "Stay at an eco-glamping lodge powered by solar energy",
    ],
    travelTips: [
      "Never feed wild animals, exit your vehicle, or make loud noises during safaris",
      "Wear neutral earthy tones (khaki, olive, brown) rather than bright neon colors",
      "Bring telephoto camera lenses (200-500mm) and high-quality binoculars",
      "Book official Department of Wildlife Conservation (DWC) registered safari jeeps",
    ],
  },
  {
    title: "Masks & Folk Traditions",
    name: "Masks & Folk Traditions",
    slug: "masks-folk-traditions",
    category: "Culture & Heritage",
    badge: "Culture",
    badgeColor: "bg-purple-600",
    shortDescription: "Discover Sri Lanka's vibrant masks, folk dances, rituals, and living cultural traditions.",
    description:
      "Centuries of coastal and up-country folklore are brought to life through Sri Lanka's iconic traditional wooden masks and dramatic ritual dances. Centered in the coastal town of Ambalangoda, master artisans hand-carve vibrant Raksha (demon), Kolam (comic folk drama), and Sanni (healing) masks from soft Kaduru wood (Strychnos nux-vomica), painting them with brilliant natural pigments. Performances such as the dynamic Kandyan dance, Sabaragamuwa dances, and low-country Pahatharata rituals showcase hypnotic drumming rhythms, acrobatic spins, and rich cultural symbolism.",
    image: "/images/culture/raksha-mask-dancers.jpg",
    images: [
      "/images/culture/raksha-mask-dancers.jpg",
      "/images/culture/traditional-raksha-masks.jpg",
      "/images/culture/ritual-demon-dance.jpg",
      "/images/culture/kandyan-dance-batik.jpg",
      "/images/culture/perahera-mural.jpg",
      "/images/culture/perahera-procession-art.jpg",
    ],
    duration: "2 to 4 Hours / Workshop Experience",
    difficulty: "Easy & Engaging",
    bestSeason: "Year-Round (Festival performances peak July-August and January-February)",
    location: "Ambalangoda, Kandy, Galle, Bentota",
    destinations: ["Galle", "Kandy", "Colombo"],
    featured: true,
    highlights: [
      "Handcrafted Ambalangoda Raksha masks representing cobras (Naga), peacocks (Mayura), and fire (Gini)",
      "Traditional Kolam dance dramas reenacting ancient royal court folklore",
      "Sanni Yakuma 18-mask spiritual healing rituals with incantations and drums",
      "Acrobatic Kandyan dancers with shimmering silver headgear and chest plates",
      "Master woodcarving workshops and mask heritage museums in Ambalangoda",
      "Intricate traditional drum rhythms played on the Geta Beraya and Yak Beraya",
    ],
    whyExperience: [
      "Discover a living art form preserved meticulously through generations",
      "Witness the extraordinary theatrical power of traditional demon dancers",
      "Learn how natural tree resins, clays, and herbal dyes create vibrant colors",
      "Support local artisan families preserving indigenous woodcarving skills",
    ],
    popularPlaces: [
      {
        name: "Ariyapala Mask Museum",
        description: "Famous ancestral mask carving museum and workshop in Ambalangoda.",
        district: "Galle",
      },
      {
        name: "Kandy Cultural Centre",
        description: "Nightly traditional Kandyan and folk dance theatrical showcases.",
        district: "Kandy",
      },
      {
        name: "Bentota Cultural Villages",
        description: "Coastal folk theater and traditional puppet drama workshops.",
        district: "Galle",
      },
      {
        name: "Galle Heritage Artisan Quarter",
        description: "Boutique artisan studios crafting collectible hand-painted folk masks.",
        district: "Galle",
      },
    ],
    thingsToDo: [
      "Attend an evening live Kandyan and Low-Country cultural dance show",
      "Take a hands-on mask carving and painting workshop in Ambalangoda",
      "Visit the historical Ariyapala Mask Museum to view rare 200-year-old masks",
      "Learn the distinctive beats of the traditional Yak Beraya drum",
      "Collect an authentic certified handmade Raksha mask for home display",
    ],
    travelTips: [
      "Look for authentic Kaduru wood masks signed by local master artisans rather than synthetic replicas",
      "Respect performers during traditional village healing rituals (Thovil)",
      "Ask permission before taking close-up portraits of costumed dancers",
      "Support heritage workshops by purchasing directly from artisan studios",
    ],
  },
  {
    title: "Night Life & Fire Pageants",
    name: "Night Life & Fire Pageants",
    slug: "night-life-fire-pageants",
    category: "Nightlife & Festivals",
    badge: "Culture",
    badgeColor: "bg-purple-600",
    shortDescription: "Experience Sri Lanka after dark with vibrant fire dances, traditional drumming, cultural pageants, and lively night events.",
    description:
      "As twilight falls across the island, Sri Lanka awakens with mesmerizing nighttime spectacles. In sacred Kandy, the annual Esala Perahera lights up the historic streets with thousands of blazing coconut-shell torches, acrobatic fire-spinners, and majestic caparisoned tuskers. Along the southern beaches of Mirissa, Unawatuna, and Hikkaduwa, beachfront dining and seafood barbecues transition into acoustic live bands and starlit oceanside lounges, while traditional southern villages hold dramatic fire-walking ceremonies (Gini Pagima) and Shanthikarma rituals under moonlit skies.",
    image: "/images/culture/ritual-demon-dance.jpg",
    images: [
      "/images/culture/ritual-demon-dance.jpg",
      "/images/destinations/kandy-temple-night-lights.jpg",
      "/images/destinations/kandy-perahera-tusker.jpg",
      "/images/culture/raksha-mask-dancers.jpg",
      "/images/culture/hindu-kovil-chariot.jpg",
      "/images/destinations/mirissa-coconut-tree-hill-sunset.jpg",
    ],
    duration: "Evening / Night Experience (3 to 6 Hours)",
    difficulty: "Exciting & Atmospheric",
    bestSeason: "July-August (Kandy Perahera) & November-April (Southern Beach Nightlife)",
    location: "Kandy, Mirissa, Colombo, Galle, Kataragama",
    destinations: ["Kandy", "Mirissa", "Colombo", "Galle"],
    featured: true,
    highlights: [
      "Asia's grandest torchlit religious pageant: Kandy Esala Perahera",
      "Dramatic Gini Sisila fire-dancing and flaming whip-cracking performances",
      "Barefoot fire-walking rituals at Kataragama and southern shrines",
      "Beachfront candlelight seafood feasts and acoustic music in Mirissa",
      "Colombo's sleek rooftop lounges with skyline views across the Indian Ocean",
      "Traditional midnight Thovil demon-dispelling rituals in village groves",
    ],
    whyExperience: [
      "Feel the visceral energy of hypnotic drums and leaping flames in the night",
      "Witness centuries-old religious pageantry illuminated by thousands of torchlights",
      "Relax with world-class cocktails at oceanside beach bars under the stars",
      "Enjoy unforgettable cultural spectacles unique to Sri Lankan heritage",
    ],
    popularPlaces: [
      {
        name: "Kandy Sacred Heritage Circuit",
        description: "Epic setting of the annual 10-night Esala Perahera torchlight pageant.",
        district: "Kandy",
      },
      {
        name: "Mirissa & Weligama Beachfront",
        description: "Vibrant beachfront seafood grills, acoustic live music, and night lounges.",
        district: "Matara",
      },
      {
        name: "Colombo Waterfront Skylines",
        description: "Chic rooftop lounges, Lotus Tower night views, and Galle Face night markets.",
        district: "Colombo",
      },
      {
        name: "Kataragama Sacred Enclosure",
        description: "Spiritual night pageants with intense fire-walking and drum devotion.",
        district: "Monaragala",
      },
    ],
    thingsToDo: [
      "Secure a front-row grandstand seat to witness the Kandy Esala Perahera",
      "Watch fearless fire-eaters and flaming baton spinners in traditional dress",
      "Dine barefoot on the sand with freshly grilled lobster under starlight",
      "Sample fiery Sri Lankan street food (Kottu & Isso Vadai) at Galle Face Green at night",
      "Listen to live acoustic musicians and Calypso bands by the ocean",
    ],
    travelTips: [
      "Reserve Kandy Perahera seats months in advance for peak festival nights in August",
      "Keep valuables secure in crowded night processions and markets",
      "Check local Poya full moon regulations when alcohol sales are prohibited",
      "Use registered meter taxis or Ride-hailing apps when traveling late at night",
    ],
  },
  {
    title: "Buy Gemstone",
    name: "Buy Gemstone",
    slug: "buy-gemstone",
    category: "Gemstones & Treasures",
    badge: "Culture",
    badgeColor: "bg-purple-600",
    shortDescription: "Discover Sri Lanka's world-famous sapphires, precious gemstones, jewellery, and traditional gem markets.",
    description:
      "Revered since antiquity as 'Ratna-Dweepa' (The Island of Gems), Sri Lanka produces over 70 of the world's 200 recognized gemstone varieties. Most celebrated is the legendary Ceylon Blue Sapphire—admired by kings, queens, and gemologists worldwide for its radiant cornflower blue clarity and brilliance. In historic Ratnapura ('City of Gems'), visitors can observe traditional pit mining, bustling open-air rough gem trading markets, master lapidaries precision-cutting gemstones on traditional wheels, and certified high-end jewellery houses in Colombo, Kandy, and Galle Fort.",
    image: "https://images.unsplash.com/photo-1515377905703-c4788e51af15?q=80&w=1200&auto=format&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1515377905703-c4788e51af15?q=80&w=1200&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1605100804763-247f67b3557e?q=80&w=1200&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?q=80&w=1200&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?q=80&w=1200&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1573408301185-9146fe634ad0?q=80&w=1200&auto=format&fit=crop",
    ],
    duration: "2 to 4 Hours / Half-Day Tour",
    difficulty: "Easy",
    bestSeason: "Year-Round",
    location: "Ratnapura, Galle Fort, Colombo, Kandy",
    destinations: ["Galle", "Colombo", "Kandy"],
    featured: true,
    highlights: [
      "World-famous Ceylon Blue Sapphires, Padparadscha, and Star Sapphires",
      "Vibrant street gem market of Ratnapura where miners trade rough stones",
      "Traditional deep alluvial gem mining pit tours in the river valleys",
      "Precision lapidary cutting, facet polishing, and bespoke jewellery setting",
      "Over 70 gem varieties including Chrysoberyl Cat's Eye, Spinel, Garnet, and Tourmaline",
      "Government Gem and Jewellery Authority (NGJA) certified gemstone testing",
    ],
    whyExperience: [
      "Purchase genuine, ethically mined precious gemstones at source prices",
      "Watch raw river gravels transformed into dazzling cut jewels by master lapidaries",
      "Own an authentic piece of Sri Lanka's royal heritage",
      "Obtain official certification guaranteeing authenticity and quality",
    ],
    popularPlaces: [
      {
        name: "Ratnapura Gem Bazaar",
        description: "The historic heart of Sri Lanka's gem mining and rough trading industry.",
        district: "Ratnapura",
      },
      {
        name: "Galle Fort Jewellery Boutiques",
        description: "Colonial mansion studios offering contemporary fine sapphire jewellery.",
        district: "Galle",
      },
      {
        name: "Colombo Gem District",
        description: "Licensed master gem dealers and National Gem and Jewellery Authority labs.",
        district: "Colombo",
      },
      {
        name: "Kandy Gem Lapidary Studios",
        description: "Educational gem museum galleries with live cutting and polishing workshops.",
        district: "Kandy",
      },
    ],
    thingsToDo: [
      "Visit an active traditional gem pit in Ratnapura to see gravel extraction",
      "Observe master lapidaries facet a rough sapphire on a rotating polishing disc",
      "Have your purchased gemstones verified at the government testing laboratory",
      "Commission a custom bespoke ring or pendant designed by master goldsmiths",
      "Explore the colorful display of rare Star Sapphires and Cat's Eyes",
    ],
    travelTips: [
      "Always demand a formal certificate from the National Gem & Jewellery Authority (NGJA) or recognized gem lab",
      "Avoid unverified street touts; buy exclusively from licensed gem merchants",
      "Inspect gemstones under natural daylight and standard 10x gemological loupes",
      "Learn the '4 Cs' (Color, Clarity, Cut, Carat) before making major purchases",
    ],
  },
  {
    title: "Dining & Seafood",
    name: "Dining & Seafood",
    slug: "dining-seafood",
    category: "Culinary & Seafood",
    badge: "Culture",
    badgeColor: "bg-purple-600",
    shortDescription: "Taste authentic Sri Lankan cuisine, from fragrant rice and curry to fresh seafood and unforgettable local flavours.",
    description:
      "Sri Lankan cuisine is a symphony of complex aromatic spices, rich coconut milk, fresh tropical produce, and bountiful ocean harvest. Signature dishes include fiery Jaffna Crab Curry, succulent lagoon prawns, Ambul Thiyal (sour fish curry), delicate bowl-shaped crispy egg hoppers (Appa), rhythmic street-side chicken and cheese kottu roti, and hearty traditional rice and curry feasts served with an array of colorful vegetable curries, dhal, and spicy Pol Sambol (coconut relish).",
    image: "https://images.unsplash.com/photo-1565557623262-b51c2513a641?q=80&w=1200&auto=format&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1565557623262-b51c2513a641?q=80&w=1200&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?q=80&w=1200&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?q=80&w=1200&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1601050690597-df0568f70950?q=80&w=1200&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1544025162-d76694265947?q=80&w=1200&auto=format&fit=crop",
    ],
    duration: "2 to 3 Hours / Culinary Tour",
    difficulty: "Delicious & Accessible",
    bestSeason: "Year-Round",
    location: "Colombo, Mirissa, Galle, Jaffna, Negombo",
    destinations: ["Colombo", "Mirissa", "Galle", "Jaffna"],
    featured: true,
    highlights: [
      "World-renowned Sri Lankan giant lagoon crab curry and grilled jumbo prawns",
      "Traditional 10-dish clay pot rice and curry feasts with fragrant spices",
      "Crispy golden bowl-shaped egg hoppers with spicy Katta Sambol",
      "Rhythmic theatrical street-food kottu roti prepared on flat iron griddles",
      "Fresh yellowfin tuna, seer fish, and calamari barbecues along coastal beaches",
      "Sweet coconut treacle, creamy Buffalo Curd, and coconut pancakes for dessert",
    ],
    whyExperience: [
      "Delight in one of the most vibrant, spice-rich culinary cultures on Earth",
      "Feast on succulent, sustainably caught wild ocean and lagoon seafood",
      "Experience hands-on village cooking over traditional wood-fired hearths",
      "Savor spicy, sweet, sour, and coconut flavors balanced to culinary perfection",
    ],
    popularPlaces: [
      {
        name: "Ministry of Crab & Old Dutch Hospital",
        description: "World-ranked iconic restaurant celebrating giant Sri Lankan mud crabs.",
        district: "Colombo",
      },
      {
        name: "Mirissa & Negombo Seafood Strips",
        description: "Beachfront open-air seafood displays with daily ocean catch.",
        district: "Matara",
      },
      {
        name: "Kandy & Galle Village Cooking Classes",
        description: "Organic farm tours followed by traditional clay pot curry cooking.",
        district: "Kandy",
      },
      {
        name: "Jaffna Cultural Restaurants",
        description: "Northern culinary haven famous for authentic black pepper crab and odiyal kool.",
        district: "Jaffna",
      },
    ],
    thingsToDo: [
      "Savor a legendary Sri Lankan black pepper or chili crab feast",
      "Learn to crack an egg into a steaming hot hopper pan in an open kitchen",
      "Order street-side cheese kottu and watch the rapid blade-chopping performance",
      "Enjoy a sunset seafood platter directly on the golden sands of Mirissa",
      "Taste fresh buffalo curd drizzled with golden Kithul palm treacle",
    ],
    travelTips: [
      "Specify your spice preference ('mild', 'medium', or 'Sri Lankan spicy') when ordering",
      "Traditional Sri Lankan meals are eaten with the right hand to appreciate textures",
      "Drink refreshing King Coconut water (Thambili) to cool your palate after spicy curries",
      "Choose busy, well-reviewed local eateries and seafood stalls with high turnover",
    ],
  },
  {
    title: "Tourist Souvenir Shops",
    name: "Tourist Souvenir Shops",
    slug: "tourist-souvenir-shops",
    category: "Shopping & Crafts",
    badge: "Culture",
    badgeColor: "bg-purple-600",
    shortDescription: "Shop for authentic Sri Lankan handicrafts, traditional masks, batik, wood carvings, and memorable gifts.",
    description:
      "Sri Lanka offers an exquisite treasure trove of artisanal handicrafts crafted through centuries-old traditions. From intricate hand-carved mahogany and teak wooden elephants, vibrant hand-dyed batik silk apparel and wall hangings, and brass oil lamps, to fragrant packaged Ceylon tea selections, natural coconut shell crafts, handmade ceramic pottery, and colorful handmade lacquerware (Laksha), shopping in Sri Lanka connects travelers directly with talented heritage artisans.",
    image: "/images/culture/souvenirs-handicrafts.jpg",
    images: [
      "/images/culture/souvenirs-handicrafts.jpg",
      "/images/culture/traditional-raksha-masks.jpg",
      "/images/culture/handicrafts-ceramics.jpg",
      "/images/culture/sri-lanka-souvenirs.jpg",
      "/images/culture/raksha-mask-dancers.jpg",
      "/images/culture/kandyan-dance-batik.jpg",
    ],
    duration: "1 to 3 Hours",
    difficulty: "Easy & Enjoyable",
    bestSeason: "Year-Round",
    location: "Colombo, Galle, Kandy, Ambalangoda",
    destinations: ["Colombo", "Galle", "Kandy"],
    featured: true,
    highlights: [
      "Hand-carved wooden elephants and protective traditional Raksha masks",
      "Exquisite handmade wax-resist Batik textiles, sarongs, and wall art",
      "Pure single-origin Ceylon tea gift boxes from Nuwara Eliya and Dimbula",
      "Hand-woven Dumbara mats and reed basketry (UNESCO Intangible Heritage)",
      "Intricate brass oil lamps, bell-metal crafts, and traditional temple bells",
      "Eco-friendly handmade paper products made from recycled elephant dung",
    ],
    whyExperience: [
      "Bring home authentic, handmade treasures that carry the soul of Sri Lanka",
      "Directly empower rural craft families, women's cooperatives, and artisans",
      "Discover unique items with rich cultural significance and history",
      "Find high-quality packaged Ceylon tea, spices, and handmade ceramics",
    ],
    popularPlaces: [
      {
        name: "Laksala State Craft Embellishments",
        description: "Official government certified handicraft emporiums across major cities.",
        district: "Colombo",
      },
      {
        name: "Galle Fort Artisan Boutiques",
        description: "Chic colonial design shops featuring designer batik, jewelry, and prints.",
        district: "Galle",
      },
      {
        name: "Kandy Arts & Crafts Association",
        description: "Historical craft guild showroom by Kandy Lake with live artisan demonstrations.",
        district: "Kandy",
      },
      {
        name: "Ambalangoda & Moratuwa Woodwork Centers",
        description: "Specialized woodcarving, furniture, and mask workshops.",
        district: "Galle",
      },
    ],
    thingsToDo: [
      "Watch a master batik artist apply hot wax and vibrant dyes onto fine fabric",
      "Select a hand-carved Kaduru wooden mask with protective blessing lore",
      "Browse certified single-estate loose leaf Ceylon black and green teas",
      "Pick up eco-friendly elephant dung paper stationery and photo albums",
      "Purchase handmade pottery and traditional brass oil lamps",
    ],
    travelTips: [
      "Look for government 'Laksala' certification or fair-trade labels to ensure quality and authenticity",
      "Polite and friendly bargaining is customary in open markets, but fixed in state emporiums",
      "Ensure wooden handicrafts are treated and dry if taking through international customs",
      "Pack delicate ceramics and brassware securely with bubble wrap",
    ],
  },
  {
    title: "Spice Gardens",
    name: "Spice Gardens",
    slug: "spice-gardens",
    category: "Nature & Botany",
    badge: "Nature",
    badgeColor: "bg-blue-600",
    shortDescription: "Walk through fragrant spice gardens and discover the cinnamon, pepper, cardamom, and herbs that shape Sri Lankan cuisine.",
    description:
      "For millennia, seafaring merchants from ancient Rome, Arabia, China, and Europe were drawn to the island's shores by the intoxicating aroma of Ceylon spices. Centered in the lush central valleys of Matale, Kandy, and the southern plains, Sri Lanka's organic spice gardens offer guided sensory walking trails. Discover how true Ceylon Cinnamon (Cinnamomum verum), fiery black pepper vines, green cardamom pods, fragrant cloves, nutmeg, vanilla, and cocoa are cultivated, harvested, and cured.",
    image: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?q=80&w=1200&auto=format&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?q=80&w=1200&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1509358271058-acd22cc93898?q=80&w=1200&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1599940824399-b87987ceb72a?q=80&w=1200&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1587049352846-4a222e784d38?q=80&w=1200&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1532336414038-cf19250c5757?q=80&w=1200&auto=format&fit=crop",
    ],
    duration: "1.5 to 3 Hours",
    difficulty: "Easy & Relaxing",
    bestSeason: "Year-Round (Harvesting is especially active May to September)",
    location: "Matale, Kandy, Balapitiya, Mawanella",
    destinations: ["Kandy", "Sigiriya", "Galle"],
    featured: true,
    highlights: [
      "Live demonstration of True Ceylon Cinnamon peeling and traditional quill rolling",
      "Climbing black and white peppercorn vines hanging from tropical forest trees",
      "Fragrant wild green cardamom plants, cloves, and mace-covered nutmeg pods",
      "Fresh cocoa pods, vanilla orchid vines, and medicinal turmeric roots",
      "Guided educational botanical tours explaining herbal culinary and medicinal properties",
      "Aromatic spice garden shops selling fresh, unadulterated ground and whole spices",
    ],
    whyExperience: [
      "Learn how world-famous spices look, smell, and grow in their natural habitat",
      "Understand the vital difference between True Ceylon Cinnamon and synthetic Cassia",
      "Enjoy a soothing herbal neck or foot massage infused with freshly extracted oils",
      "Take home vacuum-sealed fresh spices directly from source plantations",
    ],
    popularPlaces: [
      {
        name: "Matale Herbal & Spice Gardens",
        description: "The island's primary spice corridor on the highway between Kandy and Dambulla.",
        district: "Matale",
      },
      {
        name: "Balapitiya & Madu River Cinnamon Islands",
        description: "Historic river island community dedicated exclusively to pure cinnamon peeling.",
        district: "Galle",
      },
      {
        name: "Peradeniya Royal Botanical Spice Collection",
        description: "Historical spice trees planted in the royal gardens over two centuries ago.",
        district: "Kandy",
      },
      {
        name: "Mawanella Herbal Sanctuaries",
        description: "Organic village gardens showcasing indigenous Ayurvedic plants and spices.",
        district: "Kegalle",
      },
    ],
    thingsToDo: [
      "Touch, smell, and taste fresh cinnamon bark stripped straight from living branches",
      "Walk shaded nature pathways lined with towering nutmeg and clove trees",
      "Taste a cup of spiced herbal tea brewed with fresh ginger and cardamom",
      "Learn authentic spice blending ratios for traditional Sri Lankan curry powders",
      "Purchase pure cinnamon oil, vanilla extract, and therapeutic herbal balms",
    ],
    travelTips: [
      "Look for the official 'Pure Ceylon Cinnamon' lion logo on packaged spices",
      "Wear comfortable walking shoes suitable for outdoor garden trails",
      "Ask guides for clear pricing before opting for optional herbal massage demonstrations",
      "Store purchased whole spices in airtight glass containers away from direct light",
    ],
  },
  {
    title: "Camping Sites & Glamping",
    name: "Camping Sites & Glamping",
    slug: "camping-sites-glamping",
    category: "Outdoor & Adventure",
    badge: "Nature",
    badgeColor: "bg-blue-600",
    shortDescription: "Sleep beneath Sri Lanka's stars with unforgettable camping and luxury glamping experiences in forests, national parks, and scenic landscapes.",
    description:
      "From lavish safari glamping suites pitched on the edge of leopard-roamed wilderness in Yala and Udawalawe, to rugged misty mountain tent camps overlooking the Knuckles Range and Horton Plains, camping in Sri Lanka combines raw wilderness adventure with unforgettable comfort. Fall asleep to the gentle sounds of tropical nightjars, ocean waves, and rustling forest leaves, gather around glowing campfires with fellow travelers, and wake to misty sunrise panoramas and gourmet outdoor breakfasts in nature.",
    image: "https://images.unsplash.com/photo-1510312305653-8ed496efae75?q=80&w=1200&auto=format&fit=crop",
    images: [
      "https://images.unsplash.com/photo-1510312305653-8ed496efae75?q=80&w=1200&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?q=80&w=1200&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1478131143081-80f7f84ca84d?q=80&w=1200&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1523987355523-c7b5b0dd90a7?q=80&w=1200&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1517824806704-9040b037703b?q=80&w=1200&auto=format&fit=crop",
    ],
    duration: "Overnight / 2 to 4 Days Adventure",
    difficulty: "Easy (Glamping) to Moderate (Trekking Camps)",
    bestSeason: "December to April (Highlands & South) / May to September (East Coast)",
    location: "Yala, Knuckles, Udawalawe, Kitulgala, Horton Plains",
    destinations: ["Yala", "Ella", "Nuwara Eliya"],
    featured: true,
    highlights: [
      "All-inclusive luxury safari glamping tents with ensuite bathrooms and private decks",
      "Intimate wilderness camps bordering Yala, Wilpattu, and Udawalawe National Parks",
      "Scenic highland ridge camping in the UNESCO Knuckles Mountain Range",
      "Night campfire barbecues, lantern-lit dining, and guided stargazing",
      "Pre-dawn birdwatching walks directly from your tent doorstep",
      "Eco-friendly, zero-trace conservation camping principles",
    ],
    whyExperience: [
      "Immerse completely in untouched nature without sacrificing comfort",
      "Experience magical sunrise and twilight wildlife activity before park crowds arrive",
      "Unplug from digital distractions under crystal-clear starry night skies",
      "Enjoy memorable campfire tales, local BBQ grills, and wilderness luxury",
    ],
    popularPlaces: [
      {
        name: "Yala Wilderness Glamping",
        description: "Luxury air-conditioned tented camps bordering the national park buffer zone.",
        district: "Hambantota",
      },
      {
        name: "Knuckles Mountain Campsites",
        description: "Panoramic ridge-top camping surrounded by montane cloud forests.",
        district: "Matale",
      },
      {
        name: "Udawalawe Eco Tented Lodges",
        description: "Riverside tent camps where wild elephants wander near the perimeter.",
        district: "Ratnapura",
      },
      {
        name: "Kitulgala Rainforest Camping",
        description: "Riverside jungle campsites perfect for whitewater rafting and canyoning.",
        district: "Kegalle",
      },
    ],
    thingsToDo: [
      "Relax in a private plunge pool or outdoor lounge deck in your safari glamping tent",
      "Gather around the crackling evening campfire for a multi-course barbecue feast",
      "Embark on night nature walks to spot civets, owls, and nocturnal frogs",
      "Watch the sunrise paint the highland valleys in shades of gold and rose",
      "Sleep in canvas luxury listening to the soothing sounds of wild nature",
    ],
    travelTips: [
      "Pack lightweight warm clothing (fleece/jacket) for highland camping where temperatures drop at night",
      "Bring a reliable headlamp or flashlight and portable power banks",
      "Always adhere to Leave No Trace principles—never litter in national park ecosystems",
      "Book registered luxury glamping operators that include park entry permits and safari jeeps",
    ],
  },
];`;

const startMarker = 'export const seedExperiences = [';
const endMarker = 'export const seedEvents = [';

const startIndex = content.indexOf(startMarker);
const endIndex = content.indexOf(endMarker);

if (startIndex === -1 || endIndex === -1) {
  console.error('Could not find markers in seedData.ts');
  process.exit(1);
}

const newContent = content.substring(0, startIndex) + updatedExperiences + '\n\n' + content.substring(endIndex);
fs.writeFileSync(seedFile, newContent, 'utf8');
console.log('Successfully updated seedData.ts with all 12 authentic experiences!');
