const fs = require('fs');
const path = require('path');

const seedFile = path.join(__dirname, '../data/seedData.ts');
let content = fs.readFileSync(seedFile, 'utf8');

const updatedDestinations = `export const seedDestinations = [
  {
    name: "Ella",
    slug: "ella",
    province: "Uva",
    district: "Badulla",
    description:
      "A serene highland village tucked into the southern edge of Sri Lanka's central highlands, Ella is famed for emerald tea plantations, dramatic mountain gaps, cascading waterfalls, and the world-renowned Nine Arch Bridge.",
    shortDescription: "Charming highland village surrounded by misty peaks, Nine Arch Bridge, and tea estates.",
    category: "Mountains",
    heroImage: "/images/destinations/ella-nine-arch-bridge.jpg",
    images: [
      "/images/destinations/ella-nine-arch-bridge.jpg",
      "/images/destinations/ella-ravana-falls.jpg",
    ],
    latitude: 6.8667,
    longitude: 81.0466,
    bestTimeToVisit: "December to April",
    weatherSummary: "18°C - 25°C, Cool Mountain Breeze",
    attractions: ["Nine Arch Bridge", "Little Adam's Peak", "Ravana Falls", "Ella Rock", "Flying Ravana Mega Zipline"],
    activities: ["Trekking & Hiking", "Scenic Photography", "Tea Factory Tours", "Waterfall Bathing", "Train Watching"],
    featured: true,
    rating: 4.9,
    reviewsCount: 142,
    tags: ["Hiking", "Misty Hills", "Tea Country", "Scenic Train", "Waterfalls"],
  },
  {
    name: "Sigiriya",
    slug: "sigiriya",
    province: "Central",
    district: "Matale",
    description:
      "Rising nearly 200 meters above the central jungle plains, the ancient rock fortress of Sigiriya (Lion Rock) is one of UNESCO's most celebrated World Heritage Sites. Built in the 5th century CE by King Kashyapa, this archaeological masterpiece features landscaped water gardens, exquisite ancient frescoes of celestial maidens, the mirror wall inscribed with historical graffiti, and the colossal lion paw entrance at the plateau.",
    shortDescription: "The monumental 5th-century Lion Rock fortress rising dramatically above lush jungle canopies.",
    category: "Heritage",
    heroImage: "/images/destinations/sigiriya-lion-rock-monumental.jpg",
    images: [
      "/images/destinations/sigiriya-lion-rock-monumental.jpg",
      "/images/destinations/sigiriya-lion-rock-vista.jpg",
      "/images/destinations/sigiriya-lion-rock-aerial.jpg",
      "/images/destinations/sigiriya-lion-rock-mighty.jpg",
      "/images/destinations/sigiriya-pidurangala-viewpoint.jpg",
      "/images/destinations/sigiriya-water-gardens-couple.jpg",
    ],
    latitude: 7.957,
    longitude: 80.7603,
    bestTimeToVisit: "January to April",
    weatherSummary: "26°C - 32°C, Warm & Sunny",
    attractions: ["Lion Rock Citadel", "Pidurangala Rock", "Water Gardens", "Sigiriya Frescoes", "Archaeological Museum"],
    activities: ["Sunrise Rock Climbing", "Hot Air Ballooning", "Village Safari", "Ancient Architecture Discovery"],
    featured: true,
    rating: 5.0,
    reviewsCount: 230,
    tags: ["UNESCO", "Ancient Heritage", "Archaeology", "Epic Sunrises", "Lion Rock"],
  },
  {
    name: "Kandy",
    slug: "kandy",
    province: "Central",
    district: "Kandy",
    description:
      "The last royal capital of Sri Lanka, Kandy sits peacefully surrounding a picturesque lake nestled among mist-covered hills. Kandy is the spiritual heart of the island, home to the Sacred Temple of the Tooth Relic (Sri Dalada Maligawa), the royal Peradeniya Botanical Gardens, and vibrant Kandyan drumming and dance traditions.",
    shortDescription: "Sacred hill capital crowned by the Temple of the Tooth Relic, royal lake, and botanical gardens.",
    category: "Heritage",
    heroImage: "/images/destinations/kandy-temple-tooth-sunset.jpg",
    images: [
      "/images/destinations/kandy-temple-tooth-sunset.jpg",
      "/images/destinations/kandy-temple-night-lights.jpg",
      "/images/destinations/kandy-lake-couple-sunset.jpg",
      "/images/destinations/kandy-botanical-gardens-peradeniya.jpg",
      "/images/destinations/kandy-botanical-gardens-orchid.jpg",
      "/images/destinations/kandy-queens-hotel-morning.jpg",
      "/images/destinations/kandy-perahera-tusker.jpg",
    ],
    latitude: 7.2906,
    longitude: 80.6337,
    bestTimeToVisit: "December to April, July-August",
    weatherSummary: "21°C - 28°C, Gentle Mountain Climate",
    attractions: ["Temple of the Sacred Tooth Relic", "Royal Botanical Gardens Peradeniya", "Kandy Lake", "Bahirawakanda Buddha", "Ceylon Tea Museum"],
    activities: ["Cultural Dance Shows", "Lake Promenade Walking", "Botanical Exploration", "Tea Tasting"],
    featured: true,
    rating: 4.8,
    reviewsCount: 198,
    tags: ["Spiritual", "Royal Capital", "Sacred Relic", "Culture", "Lake"],
  },
  {
    name: "Mirissa",
    slug: "mirissa",
    province: "Southern",
    district: "Matara",
    description:
      "Mirissa is a quintessential crescent-shaped tropical beach paradise on Sri Lanka's southern coast. Renowned globally as one of the best locations on Earth for watching majestic Blue Whales and playful dolphins in their natural migratory corridors, Mirissa also boasts famous Coconut Tree Hill, Secret Beach, Parrot Rock, and vibrant beachfront dining under starlit skies.",
    shortDescription: "Tropical crescent beach world-famous for Coconut Tree Hill, surfing waves, and Blue Whale watching.",
    category: "Beaches",
    heroImage: "/images/destinations/mirissa-coconut-tree-hill-hills.jpg",
    images: [
      "/images/destinations/mirissa-coconut-tree-hill-hills.jpg",
      "/images/destinations/mirissa-coconut-tree-hill-amazing.jpg",
      "/images/destinations/mirissa-coconut-tree-hill-view.jpg",
      "/images/destinations/mirissa-coconut-tree-hill-ocean.jpg",
      "/images/destinations/mirissa-coconut-tree-hill-beauty.jpg",
      "/images/destinations/mirissa-coconut-tree-hill-2.jpg",
      "/images/destinations/mirissa-coconut-tree-hill-sunset.jpg",
    ],
    latitude: 5.9483,
    longitude: 80.456,
    bestTimeToVisit: "November to April",
    weatherSummary: "28°C - 32°C, Warm Ocean Sun",
    attractions: ["Coconut Tree Hill", "Mirissa Main Beach", "Parrot Rock", "Secret Beach", "Mirissa Fishery Harbour"],
    activities: ["Blue Whale Watching", "Surfing & Paddleboarding", "Sunset Photography", "Fresh Seafood Grills"],
    featured: true,
    rating: 4.9,
    reviewsCount: 167,
    tags: ["Whale Watching", "Surfing", "Beach Life", "Coconut Palms", "Sunsets"],
  },
  {
    name: "Colombo",
    slug: "colombo",
    province: "Western",
    district: "Colombo",
    description:
      "Sri Lanka's vibrant oceanfront commercial capital blends historic colonial architecture with sleek modern skyscrapers, the futuristic Colombo Port City marina, and bustling bazaar markets. Highlights include the scenic Galle Face Green promenade along the Indian Ocean, the soaring Colombo Lotus Tower, the tranquil Gangaramaya Temple and Seema Malaka on Beira Lake, the historic Colombo Fort lighthouse, and the colorful Jami Ul-Alfar Mosque in Pettah.",
    shortDescription: "Modern coastal metropolis featuring Port City marina, skyline oceanfront promenade, Lotus Tower, and historic Beira Lake temples.",
    category: "Cities",
    heroImage: "/images/destinations/colombo-red-mosque-1.jpg",
    images: [
      "/images/destinations/colombo-red-mosque-1.jpg",
      "/images/destinations/colombo-gangaramaya-temple.jpg",
      "/images/destinations/colombo-seema-malaka-bridge.jpg",
      "/images/destinations/colombo-red-mosque-2.jpg",
      "/images/destinations/colombo-red-mosque-3.jpg",
      "/images/destinations/colombo-red-mosque-4.jpg",
    ],
    latitude: 6.9271,
    longitude: 79.8612,
    bestTimeToVisit: "November to April",
    weatherSummary: "27°C - 32°C, Tropical Coastal Breeze",
    attractions: ["Colombo Port City & Marina", "Lotus Tower", "Galle Face Green", "Gangaramaya Temple & Seema Malaka", "Jami Ul-Alfar Mosque (Red Mosque)", "Colombo Fort"],
    activities: ["Port City Promenade Walk", "Lotus Tower Observation Deck", "Street Food Tasting at Galle Face", "Heritage Architecture Discovery", "Bazaar Shopping in Pettah"],
    featured: true,
    rating: 4.8,
    reviewsCount: 189,
    tags: ["Port City", "Skyline", "Capital", "Architecture", "Lotus Tower", "Waterfront"],
  },
  {
    name: "Yala",
    slug: "yala",
    province: "Southern / Uva",
    district: "Hambantota",
    description:
      "Spanning across coastal dry-zone scrub jungles and shimmering lagoons, Yala National Park boasts one of the highest leopard densities anywhere in the world. Visitors on 4x4 open safaris can witness herds of Asian elephants, elusive Sri Lankan leopards, sloth bears, marsh crocodiles, and hundreds of vibrant resident and migratory bird species.",
    shortDescription: "Premier national park with the world's highest density of leopards and rich safari wildlife.",
    category: "Wildlife",
    heroImage: "/images/destinations/yala-leopard-tree.jpg",
    images: [
      "/images/destinations/yala-leopard-portrait.jpg",
      "/images/destinations/yala-leopard-tree.jpg",
      "/images/destinations/yala-safari-jeep-gathering.jpg",
      "/images/destinations/yala-elephant-family.jpg",
      "/images/destinations/yala-elephants-sunset.jpg",
    ],
    latitude: 6.368,
    longitude: 81.5273,
    bestTimeToVisit: "February to June",
    weatherSummary: "27°C - 34°C, Dry Savannah Sunshine",
    attractions: ["Yala Block 1", "Patanangala Beach", "Kithulgala Lagoon", "Sithulpawwa Rock Temple", "Magul Maha Viharaya"],
    activities: ["4x4 Leopard Safari", "Bird Watching", "Eco Glamping", "Wildlife Photography"],
    featured: true,
    rating: 4.9,
    reviewsCount: 215,
    tags: ["Leopards", "Safari", "Elephants", "Wilderness", "Big Game"],
  },
  {
    name: "Nuwara Eliya",
    slug: "nuwara-eliya",
    province: "Central",
    district: "Nuwara Eliya",
    description:
      "Nestled 1,868 meters above sea level beneath Mount Pidurutalagala, Nuwara Eliya is Sri Lanka's celebrated highland retreat. Famed for its cool alpine climate, manicured rolling Ceylon tea estates, Lake Gregory, cascading waterfalls like Lovers Leap, Victorian Tudor-style bungalows, and historic British colonial heritage, it offers a refreshing mountain paradise unlike anywhere else on the island.",
    shortDescription: "Alpine mountain sanctuary of verdant Ceylon tea gardens, Lake Gregory, Tudor colonial estates, and cool highland mist.",
    category: "Mountains",
    heroImage: "/images/destinations/nuwara-eliya-tea-gardens.jpg",
    images: [
      "/images/destinations/nuwara-eliya-tea-gardens.jpg",
      "/images/destinations/nuwara-eliya-gregory-lake-1.jpg",
      "/images/destinations/nuwara-eliya-gregory-lake-2.jpg",
      "/images/destinations/nuwara-eliya-gregory-lake-park.jpg",
      "/images/destinations/nuwara-eliya-post-office.jpg",
      "/images/destinations/nuwara-eliya-adisham-bungalow.jpg",
      "/images/destinations/nuwara-eliya-tudor-cottages.jpg",
    ],
    latitude: 6.9497,
    longitude: 80.7891,
    bestTimeToVisit: "February to May",
    weatherSummary: "10°C - 20°C, Crisp Alpine Climate",
    attractions: ["Pedro Tea Estate", "Lake Gregory", "Historic Post Office", "Victoria Park", "Horton Plains & World's End", "Lovers Leap Waterfall", "Adisham Bungalow"],
    activities: ["Ceylon Tea Tasting", "Heritage Bungalow Tour", "Lake Boating & Cycling", "Horton Plains Trekking", "Golfing"],
    featured: true,
    rating: 4.8,
    reviewsCount: 148,
    tags: ["Ceylon Tea", "Highlands", "Lake Gregory", "Horton Plains", "Crisp Air", "Colonial Heritage"],
  },
  {
    name: "Arugam Bay",
    slug: "arugam-bay",
    province: "Eastern",
    district: "Ampara",
    description:
      "A world-renowned surf mecca on Sri Lanka's sunny eastern coastline, Arugam Bay delivers legendary right-hand point breaks, relaxed bohemian beach cafes, and easy access to Kumana National Park's bird sanctuaries and elephant corridors.",
    shortDescription: "International surf capital with world-class point breaks and laid-back coastal vibes.",
    category: "Beaches",
    heroImage: "/images/destinations/arugam-bay-2.jpg",
    images: [
      "/images/destinations/arugam-bay-2.jpg",
      "/images/destinations/arugam-bay-fishing-boats-sunset.jpg",
      "/images/destinations/arugam-bay-1.jpg",
    ],
    latitude: 6.843,
    longitude: 81.829,
    bestTimeToVisit: "May to September",
    weatherSummary: "29°C - 34°C, Sunny Offshore Surfing Weather",
    attractions: ["Main Point Surf Break", "Elephant Rock", "Whiskey Point", "Peanut Farm Beach", "Kumana National Park"],
    activities: ["World-Class Surfing", "Lagoon Boat Safaris", "Yoga Retreats", "Sunset Rock Climbing"],
    featured: true,
    rating: 4.8,
    reviewsCount: 110,
    tags: ["Surfing", "East Coast", "Bohemian", "Point Breaks", "Sun & Sea"],
  },
  {
    name: "Polonnaruwa",
    slug: "polonnaruwa",
    province: "North Central",
    district: "Polonnaruwa",
    description:
      "The splendid 10th-century medieval capital of Sri Lanka, Polonnaruwa is a UNESCO World Heritage Site renowned for its remarkably preserved royal palaces, ancient stupas, giant artificial reservoir (Parakrama Samudra), and monumental rock carvings at Gal Vihara. The famous Polonnaruwa Vatadage—a circular relic house with exquisite moonstones and stone guardstones—stands as one of the apex architectural achievements of ancient Sri Lanka.",
    shortDescription: "Medieval UNESCO royal capital famed for the circular Vatadage, Gal Vihara rock statues, and colossal reservoirs.",
    category: "Heritage",
    heroImage: "/images/destinations/polonnaruwa-vatadage-1.jpg",
    images: [
      "/images/destinations/polonnaruwa-vatadage-1.jpg",
      "/images/destinations/polonnaruwa-vatadage-2.jpg",
    ],
    latitude: 7.9403,
    longitude: 81.0188,
    bestTimeToVisit: "May to September, December to March",
    weatherSummary: "27°C - 33°C, Sunny Plain",
    attractions: ["Polonnaruwa Vatadage", "Gal Vihara Rock Statues", "Parakrama Samudra Lake", "Royal Palace of King Parakramabahu", "Nissanka Latha Mandapaya"],
    activities: ["Bicycle Heritage Exploration", "Ancient Architecture Photography", "Lake Breeze Walks", "Archaeological Museum Tour"],
    featured: true,
    rating: 4.9,
    reviewsCount: 176,
    tags: ["UNESCO", "Vatadage", "Ancient Citadel", "Gal Vihara", "Medieval Capital"],
  },
  {
    name: "Jaffna",
    slug: "jaffna",
    province: "Northern",
    district: "Jaffna",
    description:
      "Located at the northernmost tip of Sri Lanka, Jaffna is a culturally rich and vibrant peninsula defined by ancient Tamil Kovils, majestic Dutch forts, secluded islands like Nainativu and Delft, and delicious authentic northern cuisine. The iconic Nallur Kandaswamy Kovil, with its magnificent colorful Gopuram tower, stands as the spiritual heart of the northern region.",
    shortDescription: "Northern cultural peninsula famous for towering ornate Hindu Kovils, historic forts, and island vistas.",
    category: "Heritage",
    heroImage: "/images/destinations/jaffna-kovil-1.jpg",
    images: [
      "/images/destinations/jaffna-kovil-1.jpg",
      "/images/destinations/jaffna-kovil-tuktuk.jpg",
    ],
    latitude: 9.6615,
    longitude: 80.0255,
    bestTimeToVisit: "January to September",
    weatherSummary: "28°C - 34°C, Warm Tropical Sunshine",
    attractions: ["Nallur Kandaswamy Kovil", "Jaffna Fort", "Nagadeepa / Nainativu Island", "Casuarina Beach", "Keerimalai Holy Springs"],
    activities: ["Temple Pilgrimage & Rituals", "Island Ferry Excursions", "Jaffna Crab Curry Tasting", "Colonial History Walking"],
    featured: true,
    rating: 4.8,
    reviewsCount: 142,
    tags: ["Northern Capital", "Hindu Kovil", "Nallur", "Culture", "Islands"],
  },
  {
    name: "Galle",
    slug: "galle",
    province: "Southern",
    district: "Galle",
    description:
      "A UNESCO World Heritage Site on the southern coast, Galle Fort is Asia's best-preserved European sea fortress. Built by the Portuguese in 1588 and fortified by the Dutch in the 17th century, Galle Fort features cobbled ramparts overlooking the Indian Ocean, a historic lighthouse, boutique cafes, art galleries, and colonial Dutch architecture.",
    shortDescription: "Historic 16th-century oceanfront Dutch fortress, UNESCO World Heritage ramparts, and iconic lighthouse.",
    category: "Heritage",
    heroImage: "/images/destinations/galle-fort-lighthouse.jpg",
    images: [
      "/images/destinations/galle-fort-lighthouse.jpg",
      "/images/destinations/galle-fort-crafts.jpg",
      "/images/destinations/galle-fort-pedlars-cafe.jpg",
    ],
    latitude: 6.0535,
    longitude: 80.221,
    bestTimeToVisit: "December to April",
    weatherSummary: "28°C - 32°C, Balmy Ocean Breeze",
    attractions: ["Galle Fort Lighthouse", "Dutch Ramparts", "Old Dutch Hospital", "National Maritime Museum", "Flag Rock Bastion"],
    activities: ["Rampart Sunset Walks", "Colonial Boutique Shopping", "Lighthouse Photography", "Gem & Jewelry Discovery"],
    featured: true,
    rating: 4.9,
    reviewsCount: 195,
    tags: ["UNESCO", "Dutch Fort", "Lighthouse", "Colonial Architecture", "Coastal Ramparts"],
  },
  {
    name: "Pinnawala",
    slug: "pinnawala",
    province: "Sabaragamuwa",
    district: "Kegalle",
    description:
      "Established in 1975, the Pinnawala Elephant Orphanage is an internationally celebrated sanctuary for orphaned, injured, and abandoned Asian elephants. Located along the scenic banks of the Maha Oya River, visitors can witness heartwarming daily river bathing rituals, bottle feeding of baby calves, and large multi-generational herds roaming together peacefully.",
    shortDescription: "Renowned elephant sanctuary along the Maha Oya River famous for daily elephant river bathing rituals.",
    category: "Wildlife",
    heroImage: "/images/destinations/pinnawala-elephants-river.jpg",
    images: [
      "/images/destinations/pinnawala-elephants-river.jpg",
      "/images/destinations/pinnawala-river-view-2.jpg",
      "/images/destinations/pinnawala-riverfront-breakfast.jpg",
    ],
    latitude: 7.2996,
    longitude: 80.3867,
    bestTimeToVisit: "Year-Round (Bathing at 10 AM & 2 PM)",
    weatherSummary: "26°C - 31°C, Tropical River Basin",
    attractions: ["Maha Oya River Bathing Site", "Elephant Nursery Pavilion", "Elephant Dung Paper Factory", "Pinnawala Open Zoo"],
    activities: ["River Bathing Viewing", "Baby Elephant Milk Feeding", "Eco-Paper Workshop Tour", "Wildlife Photography"],
    featured: true,
    rating: 4.8,
    reviewsCount: 168,
    tags: ["Elephants", "Sanctuary", "River Bathing", "Wildlife Care", "Family Friendly"],
  },
  {
    name: "Anuradhapura",
    slug: "anuradhapura",
    province: "North Central",
    district: "Anuradhapura",
    description:
      "The first great ancient capital of Sri Lanka flourished for over a millennium. Anuradhapura is home to giant brick stupas (Ruwanwelisaya, Jetavanaramaya) that rival Egypt's pyramids in mass, intricate moonstones, and the Jaya Sri Maha Bodhi—the oldest historically recorded human-planted tree in the world.",
    shortDescription: "Sacred ancient kingdom of colossal Buddhist stupas, holy Bodhi tree, and monastic wonders.",
    category: "Heritage",
    heroImage: "/images/destinations/polonnaruwa-vatadage-1.jpg",
    images: [
      "/images/destinations/polonnaruwa-vatadage-1.jpg",
      "/images/destinations/polonnaruwa-vatadage-2.jpg",
    ],
    latitude: 8.3114,
    longitude: 80.4037,
    bestTimeToVisit: "June to September, December to March",
    weatherSummary: "28°C - 33°C, Warm Tropical Plain",
    attractions: ["Ruwanwelisaya Stupa", "Jaya Sri Maha Bodhi", "Jetavanaramaya", "Abhayagiri Monastery", "Twin Ponds (Kuttam Pokuna)"],
    activities: ["Bicycle Pilgrimage", "Archaeological Exploration", "Meditation & Temple Blessings"],
    featured: false,
    rating: 4.9,
    reviewsCount: 135,
    tags: ["Ancient Capital", "Sacred Bodhi", "Giant Stupas", "UNESCO", "Pilgrimage"],
  },
  {
    name: "Trincomalee",
    slug: "trincomalee",
    province: "Eastern",
    district: "Trincomalee",
    description:
      "Blessed with one of the finest natural deep-water harbors in the world, Trincomalee features powder-white beaches at Nilaveli, vibrant coral reef snorkeling at Pigeon Island, and the cliffside Hindu temple Koneswaram perched high above Swami Rock.",
    shortDescription: "East coast paradise of turquoise bays, Pigeon Island coral reefs, and cliffside Koneswaram temple.",
    category: "Beaches",
    heroImage: "/images/destinations/trincomalee-swami-rock-bay.jpg",
    images: [
      "/images/destinations/trincomalee-swami-rock-bay.jpg",
      "/images/destinations/trincomalee-koneswaram-shiva.jpg",
      "/images/destinations/trincomalee-swami-rock-stairs.jpg",
    ],
    latitude: 8.5874,
    longitude: 81.2152,
    bestTimeToVisit: "March to October",
    weatherSummary: "29°C - 34°C, Crystal Clear Waters",
    attractions: ["Koneswaram Temple", "Pigeon Island National Park", "Nilaveli Beach", "Fort Frederick", "Marble Beach"],
    activities: ["Coral Reef Snorkeling", "Scuba Diving with Sharks & Turtles", "Whale Watching", "Temple Exploration"],
    featured: false,
    rating: 4.8,
    reviewsCount: 94,
    tags: ["Pigeon Island", "Snorkeling", "Coral Reefs", "Hindu Temple", "Deep Harbor"],
  },
  {
    name: "Umandawa",
    slug: "umandawa",
    province: "North Western",
    district: "Kurunegala",
    description:
      "Umandawa Global Buddhist Village is an innovative eco-spiritual monastery and agro-tourism village situated near Melsiripura in the Kurunegala district. Spanning across lush rolling landscapes, Umandawa blends Buddhist philosophy, mindful meditation retreats, self-sufficient organic agriculture, traditional architecture, and tranquil lotus ponds. Visitors can experience sustainable living, serene stupa shrines, and cultural exhibitions amidst pristine natural surroundings.",
    shortDescription: "Serene eco-spiritual Buddhist village featuring organic gardens, meditation sanctuaries, and traditional architecture.",
    category: "Heritage",
    heroImage: "/images/destinations/umandawa-reclining-buddha.jpg",
    images: [
      "/images/destinations/umandawa-reclining-buddha.jpg",
      "/images/destinations/umandawa-reclining-statue.jpg",
      "/images/destinations/umandawa-tunnel-viharaya.jpg",
    ],
    latitude: 7.6433,
    longitude: 80.4683,
    bestTimeToVisit: "Year-Round",
    weatherSummary: "26°C - 31°C, Pleasant Breeze & Tropical Greenery",
    attractions: ["Umandawa Monastery Shrine", "Organic Agro-Farming Fields", "Meditation Pavilions", "Lotus Lake & Water Gardens", "Cultural Heritage Village"],
    activities: ["Mindfulness & Meditation Retreats", "Organic Farming Tours", "Eco-Village Exploration", "Spiritual Architecture Photography"],
    featured: true,
    rating: 4.9,
    reviewsCount: 124,
    tags: ["Eco Sanctuary", "Meditation", "Buddhist Village", "Organic Farming", "Spirituality", "Nature"],
  },
  {
    name: "Namal Angana Viharaya",
    slug: "namal-angana-viharaya",
    province: "North Western",
    district: "Kurunegala",
    description:
      "Namal Angana Viharaya is a historically significant Buddhist temple located in the North Western Province of Sri Lanka. Renowned for its tranquil monastic ambiance, peaceful Buddha statues, traditional temple architecture, and scenic natural setting, the viharaya provides a serene environment for spiritual contemplation, religious ceremonies, and appreciation of ancient Sri Lankan religious heritage.",
    shortDescription: "Historic Buddhist sanctuary featuring serene shrine rooms, ancient monastic architecture, and peaceful lotus gardens.",
    category: "Heritage",
    heroImage: "/images/destinations/namal-angana-temple-shrine.jpg",
    images: [
      "/images/destinations/namal-angana-temple-shrine.jpg",
      "/images/destinations/namal-angana-ancient-stupa.jpg",
      "/images/destinations/namal-angana-sacred-forest.jpg",
      "/images/destinations/namal-angana-temple-grounds.jpg",
      "/images/destinations/namal-angana-monastic-ruins.jpg",
    ],
    latitude: 7.4812,
    longitude: 80.3621,
    bestTimeToVisit: "Year-Round",
    weatherSummary: "27°C - 32°C, Warm Tropical Sunlight",
    attractions: ["Main Shrine Room & Buddha Statues", "Sacred Bo Tree Shrine", "Ancient Stupa", "Temple Lotus Gardens", "Meditation Groves"],
    activities: ["Temple Pilgrimage & Blessings", "Religious Murals Discovery", "Mindful Walking in Nature", "Historical Photography"],
    featured: false,
    rating: 4.8,
    reviewsCount: 96,
    tags: ["Buddhist Temple", "Monastery", "Spiritual", "Heritage", "Serene", "Sacred"],
  },
  {
    name: "Tri-Forces Museum",
    slug: "tri-forces-museum",
    province: "Western",
    district: "Colombo",
    description:
      "The Sri Lanka Tri-Forces Museum is an esteemed national military heritage museum that honors and preserves the history, valor, and technological evolution of the Sri Lanka Army, Sri Lanka Navy, and Sri Lanka Air Force. The complex features carefully curated historical galleries, vintage aircraft, naval defense artifacts, armored vehicles, and ceremonial exhibits detailing Sri Lanka's defense heritage and United Nations peacekeeping contributions.",
    shortDescription: "Official national defense heritage museum showcasing Sri Lanka's Army, Navy, and Air Force historical milestones and equipment.",
    category: "Heritage",
    heroImage: "/images/destinations/tri-forces-museum-exterior-aircraft.jpg",
    images: [
      "/images/destinations/tri-forces-museum-exterior-aircraft.jpg",
      "/images/destinations/tri-forces-museum-mil24-helicopter.jpg",
      "/images/destinations/tri-forces-museum-hangar-exhibit.jpg",
      "/images/destinations/tri-forces-museum-aircraft-display.jpg",
      "/images/destinations/tri-forces-museum-interior-gallery.jpg",
    ],
    latitude: 6.8782,
    longitude: 79.9015,
    bestTimeToVisit: "Year-Round",
    weatherSummary: "27°C - 32°C, Pleasant Coastal Weather",
    attractions: ["Air Force Aviation Exhibits", "Naval Heritage Pavilion", "Army Armored Equipment Displays", "Peacekeeping Memorial Gallery", "Historical Uniforms Collection"],
    activities: ["Military History Exploration", "Aviation & Aircraft Viewing", "Educational Guided Tours", "Memorial Grounds Walk"],
    featured: false,
    rating: 4.7,
    reviewsCount: 115,
    tags: ["Military Museum", "Aviation", "Naval", "Defense Heritage", "History", "Educational"],
  },
  {
    name: "Munneswaram Kovil",
    slug: "munneswaram-kovil",
    province: "North Western",
    district: "Puttalam",
    description:
      "Munneswaram Kovil is one of the five ancient Pancha Ishwarams dedicated to Lord Shiva across Sri Lanka, dating back millennia and steeped in the epic legends of the Ramayana. Located near Chilaw in the Puttalam District, this sacred Hindu temple complex is famed for its monumental Dravidian Gopuram tower adorned with hundreds of vibrant deity sculptures, its tranquil temple holy pond (Theertham), ornate pillared halls, and colorful annual Chariot Festival.",
    shortDescription: "Ancient Pancha Ishwaram Hindu temple complex dedicated to Lord Shiva with towering Dravidian Gopuram architecture.",
    category: "Heritage",
    heroImage: "/images/destinations/munneswaram-kovil-gopuram.jpg",
    images: [
      "/images/destinations/munneswaram-kovil-gopuram.jpg",
      "/images/destinations/munneswaram-kovil-sanctum.jpg",
      "/images/destinations/munneswaram-kovil-ganesha.jpg",
      "/images/destinations/munneswaram-kovil-sharabha.jpg",
    ],
    latitude: 7.5816,
    longitude: 79.8167,
    bestTimeToVisit: "August to September (Festival Season), Year-Round",
    weatherSummary: "28°C - 33°C, Warm Sunny Coastal Plains",
    attractions: ["Main Shiva Temple Sanctum", "Towering Multi-Tiered Gopuram", "Sacred Temple Pond (Theertham)", "Ganesha & Kali Shrines", "Ramayana Heritage Site"],
    activities: ["Hindu Temple Pooja Rituals", "Gopuram Architectural Photography", "Chariot Festival Celebration", "Spiritual Pilgrimage"],
    featured: true,
    rating: 4.9,
    reviewsCount: 158,
    tags: ["Hindu Temple", "Lord Shiva", "Pancha Ishwaram", "Gopuram", "Ramayana", "Heritage"],
  },
  {
    name: "Seruwawila",
    slug: "seruwawila",
    province: "Eastern",
    district: "Trincomalee",
    description:
      "Seruwawila Mangala Raja Maha Viharaya is a revered ancient Buddhist temple complex located in the Trincomalee District of Eastern Sri Lanka. Constructed in the 2nd century BCE by King Kavantissa, this sacred pilgrimage shrine enshrines the sacred forehead bone relic (Lalata Dathu) of Gautama Buddha. Surrounded by lush wetlands and tranquil archaeological ruins, Seruwawila stands as one of the 16 sacred Solosmasthana shrines of Sri Lanka.",
    shortDescription: "Ancient 2nd-century BCE sacred stupa housing the forehead bone relic (Lalata Dathu) of Gautama Buddha.",
    category: "Heritage",
    heroImage: "/images/destinations/seruwawila-stupa-main.jpg",
    images: [
      "/images/destinations/seruwawila-stupa-main.jpg",
      "/images/destinations/seruwawila-temple-ruins.jpg",
    ],
    latitude: 8.3755,
    longitude: 81.3167,
    bestTimeToVisit: "March to October, December to February",
    weatherSummary: "28°C - 33°C, Sunny Eastern Dry Zone",
    attractions: ["Mangala Raja Maha Stupa", "Sacred Lalata Dathu Relic Chamber", "Ancient Archaeological Stone Ruins", "Makara Thorana Entrance Arch", "Allai Tank Nature Basin"],
    activities: ["Solosmasthana Pilgrimage", "Ancient Archaeological Exploration", "Meditation in Monastic Groves", "Scenic Eastern Plains Photography"],
    featured: true,
    rating: 4.9,
    reviewsCount: 138,
    tags: ["Sacred Relic", "Ancient Stupa", "Solosmasthana", "King Kavantissa", "Pilgrimage", "UNESCO Candidate"],
  },
  {
    name: "Arantalawa",
    slug: "arantalawa",
    province: "Eastern",
    district: "Ampara",
    description:
      "Arantalawa is a historic Buddhist monastery and International Peace Centre located in the Ampara District of Eastern Sri Lanka. Set amidst peaceful dry-zone forested scenery along the Maha Oya corridor, Arantalawa features a magnificent peace memorial stupa, monastic meditation halls, serene Buddha statues, and tranquil gardens that symbolize resilience, compassion, and non-violence.",
    shortDescription: "Sacred Buddhist monastery and international peace memorial promoting compassion, harmony, and spiritual serenity.",
    category: "Heritage",
    heroImage: "/images/destinations/arantalawa-peace-memorial.jpg",
    images: [
      "/images/destinations/arantalawa-peace-memorial.jpg",
      "/images/destinations/arantalawa-mahavapi-viharaya.jpg",
    ],
    latitude: 7.5458,
    longitude: 81.4219,
    bestTimeToVisit: "March to October",
    weatherSummary: "27°C - 33°C, Warm & Peaceful Eastern Climate",
    attractions: ["Arantalawa Peace Memorial Stupa", "Buddha Statue Pavilion", "Memorial Heritage Hall", "Monastic Meditation Grounds", "Scenic Eastern Landscape"],
    activities: ["Spiritual Contemplation", "Peace Memorial Pilgrimage", "Nature & Monastery Walking", "Mindfulness Practice"],
    featured: false,
    rating: 4.8,
    reviewsCount: 102,
    tags: ["Peace Memorial", "Buddhist Monastery", "Spiritual", "Heritage", "Eastern Province", "Meditation"],
  },
  {
    name: "Maha Oya Hot Water Springs",
    slug: "maha-oya-hot-water-springs",
    province: "Eastern",
    district: "Ampara",
    description:
      "Maha Oya Hot Water Springs is one of Sri Lanka's most renowned geothermal natural wonders, situated in the Eastern Province near the town of Maha Oya. The site features seven distinct natural thermal spring wells enclosed by stone masonry, each naturally emerging from deep subterranean aquifers at varying warm temperatures ranging from 37°C to 56°C. Revered for centuries for their therapeutic mineral-rich waters, the springs provide a unique wellness bathing and nature experience.",
    shortDescription: "Natural geothermal hot springs featuring seven thermal water wells with distinct temperatures in a serene tropical setting.",
    category: "Nature",
    heroImage: "/images/destinations/maha-oya-hot-springs-wells.jpg",
    images: [
      "/images/destinations/maha-oya-hot-springs-wells.jpg",
      "/images/destinations/maha-oya-thermal-wells-detail.jpg",
      "/images/destinations/maha-oya-hot-springs-baths.jpg",
      "/images/destinations/maha-oya-landscape.jpg",
      "/images/destinations/maha-oya-maduru-oya-dam.jpg",
    ],
    latitude: 7.5342,
    longitude: 81.3486,
    bestTimeToVisit: "Year-Round (Early Mornings & Evenings)",
    weatherSummary: "28°C - 34°C, Warm Tropical Climate",
    attractions: ["Seven Thermal Hot Water Wells", "Natural Mineral Bathing Enclosures", "Tropical Forest Nature Trail", "Maha Oya River Basin", "Local Handicraft Stalls"],
    activities: ["Thermal Mineral Bathing", "Geothermal Nature Exploration", "Wellness & Relaxation", "Scenic Nature Photography"],
    featured: true,
    rating: 4.8,
    reviewsCount: 119,
    tags: ["Hot Springs", "Geothermal", "Thermal Wells", "Wellness", "Nature", "Healing Waters"],
  },
  {
    name: "Nilaveli Beach",
    slug: "nilaveli-beach",
    province: "Eastern",
    district: "Trincomalee",
    description:
      "Nilaveli Beach is considered one of the purest and most breathtaking stretches of coastline in all of Asia. Located just north of Trincomalee, Nilaveli is celebrated for its powder-soft white sands, crystal-clear turquoise waters that stay gently shallow for hundreds of meters into the sea, and swaying coconut palms. It also serves as the primary coastal launch point for boat excursions to Pigeon Island National Park, where travelers snorkel amidst vibrant coral reefs, blacktip reef sharks, and sea turtles.",
    shortDescription: "Pristine East Coast paradise renowned for powdery white sands, shallow turquoise waters, and gateway to Pigeon Island National Park.",
    category: "Beaches",
    heroImage: "/images/destinations/nilaveli-beach-white-sands.jpg",
    images: [
      "/images/destinations/nilaveli-beach-white-sands.jpg",
      "/images/destinations/nilaveli-beach-coastline.jpg",
      "/images/destinations/nilaveli-beach-pigeon-island-view.jpg",
      "/images/destinations/nilaveli-beach-shore.jpg",
    ],
    latitude: 8.6872,
    longitude: 81.1964,
    bestTimeToVisit: "March to October",
    weatherSummary: "29°C - 34°C, Crystal Clear Ocean & Sun",
    attractions: ["Nilaveli White Sand Beach", "Pigeon Island National Park", "Coral Reef Snorkeling Sites", "Red Rock Beach", "Dutch Bay"],
    activities: ["Snorkeling with Sea Turtles & Reef Sharks", "Scuba Diving", "Sunbathing & Ocean Swimming", "Boat Tours to Pigeon Island", "Seafood Beach Dining"],
    featured: true,
    rating: 4.9,
    reviewsCount: 184,
    tags: ["White Sand Beach", "Pigeon Island", "Coral Reefs", "Snorkeling", "Turquoise Waters", "East Coast"],
  },
];`;

const startMarker = 'export const seedDestinations = [';
const endMarker = 'export const seedExperiences = [';

const startIndex = content.indexOf(startMarker);
const endIndex = content.indexOf(endMarker);

if (startIndex === -1 || endIndex === -1) {
  console.error('Could not find markers in seedData.ts');
  process.exit(1);
}

const newContent = content.substring(0, startIndex) + updatedDestinations + '\n\n' + content.substring(endIndex);
fs.writeFileSync(seedFile, newContent, 'utf8');
console.log('Successfully updated seedData.ts with authentic destination photos!');
